#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
# contains the string Ceci n'est pas une page.

printf "\nUpdating package list...\n"
sudo apt-get -y update

printf "\nInstalling Nginx...\n"
sudo apt-get -y install nginx

printf "\nCreating a basic 'Hello World!' index.html page...\n"
echo 'Hello World!' | sudo tee /var/www/html/index.html

printf "\nCreating a custom 404 error page...\n"
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf "\nConfiguring Nginx to handle 404 errors...\n"
sudo sed -i '/server_name _;/a error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo sed -i '/location = \/404.html {/a internal;' /etc/nginx/sites-available/default

printf "\nStarting Nginx service...\n"
sudo service nginx start
