#!/usr/bin/env bash
# display bad luck for the 4th  and good luck for 8th loop

i=1

while (( i<=10 )); do
	if (( i == 4 )); then
		echo "bad luck"
	elif (( i == 8 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
