#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.#!/usr/bin/env bash.

# Make a copy of the original hosts file
sudo cp /etc/hosts ~/hosts.new

# Modify the copy of the hosts file to change localhost resolution
sudo sed -i 's/127.0.0.1.*/127.0.0.2 localhost/' ~/hosts.new

# Add an entry for facebook.com resolving to 8.8.8.8 in the copy of hosts file
echo "8.8.8.8		facebook.com" >> ~/hosts.new

# Overwrite the original hosts file with the modified copy
sudo cp -f ~/hosts.new /etc/hosts
