#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
#+ localhost resolves to 127.0.0.2
#+ facebook.com resolves to 8.8.8.8.#!/usr/bin/env bash.

# Configure localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1.*/127.0.0.2 localhost/' /etc/hosts

# Add an entry for facebook.com resolving to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts >/dev/null

