#!/usr/bin/env bash
# script should run the whoami command under the user passed as an arg

# Use 'sudo' to switch to the specified user and then run 'whoami' to
# --determine the current user
sudo -u "$1" whoami
