#!/usr/bin/env bash
# Write a Bash script that creates an RSA key pair.
# +Name of the created private key must be school
# +Number of bits in the created key to be created 4096
# +The created key must be protected by the passphrase betty

private_key_name="school"
bit_num=4096
pass_phrase="betty"

ssh-keygen -b "$bit_num" -f "$private_key_name" -N "$pass_phrase"
